linters-settings:
  exhaustruct:
    exclude:
    - 'dynamodb\.'
    - 'events\.APIGatewayProxyRequest$'
    - 'events\.APIGatewayProxyResponse$'
    - 'mocks\.'
    - 'listResponse$'

  gci:
    sections:
    - standard # Standard section: captures all standard packages.
    - default # Default section: contains all imports that could not be matched to another section type.
    - prefix(github.com/abtercms/abtercms2) # Custom section: groups all imports with the specified Prefix.

  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 180
    # Tab width in spaces.
    # Default: 1
    tab-width: 4

  tagliatelle:
    case:
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake

  varnamelen:
    ignore-decls:
    - h handler

  wrapcheck:
    ignoreSigs:
    - .Errorf(
    - errors.New(
    - errors.Unwrap(
    - .Wrap(
    - .Wrapf(
    - .WithMessage(
    - .WithMessagef(
    - .WithStack(
    - .WrapProblem(

linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
  disable:
  - exhaustivestruct
  - golint
  - gofumpt
  - interfacer
  - maligned
  - scopelint

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: handler\.go
    linters:
    - wrapcheck
  - path: _test\.go
    linters:
    - funlen
