linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 8
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 5.0
    # Should ignore tests.
    # Default: false
    skip-tests: true

  exhaustruct:
    exclude:
    - 'dynamodb\.'
    - 'events\.APIGatewayProxyRequest$'
    - 'events\.APIGatewayProxyResponse$'
    - 'listResponse$'

  gci:
    sections:
    - standard # Standard section: captures all standard packages.
    - default # Default section: contains all imports that could not be matched to another section type.
    - prefix(github.com/abtercms/abtercms2) # Custom section: groups all imports with the specified Prefix.

  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 180
    # Tab width in spaces.
    # Default: 1
    tab-width: 4

  tagliatelle:
    case:
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake

  varnamelen:
    ignore-decls:
    - h handler

  wrapcheck:
    ignoreSigs:
    - .Errorf(
    - errors.New(
    - errors.Unwrap(
    - .Wrap(
    - .Wrapf(
    - .WithMessage(
    - .WithMessagef(
    - .WithStack(
    - .WrapProblem(

linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
  disable:
  - exhaustivestruct
  - golint
  - gofumpt
  - interfacer
  - maligned
  - paralleltest
  - scopelint

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
  # Exclude some linters from running on tests files.
  - path: handler\.go
    linters:
    - wrapcheck
  - path: _test\.go
    linters:
    - dupl
    - exhaustruct
    - funlen
    - goerr113
    - nosnakecase
    - varnamelen
  - path: _test\.go
    text: "context-keys-type"
    linters:
    - revive
  - path: _test\.go
    text: "SA1029:"
    linters:
    - staticcheck
  - path: _test\.go
    text: "assignments should only be cuddled with other assignments"
    linters:
    - wsl
  - path: _test\.go
    text: "only one cuddle assignment allowed before range statement"
    linters:
    - wsl