AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  websites
  
  Sample SAM Template for websites

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  WebsitesTable:
    Type: String
    Description: has
    Default: websites

Resources:
  WebsitesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: websites/
      Handler: websites
      Runtime: go1.x
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref WebsitesTable
      Architectures:
      - x86_64
      Events:
        ListWebsites:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /websites
            Method: GET
        CreateWebsite:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /websites
            Method: POST
        GetWebsite:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /websites/{id}
            Method: GET
        UpdateWebsite:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /websites/{id}
            Method: PUT
        DeleteWebsite:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /websites/{id}
            Method: DELETE
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE_NAME: !Ref WebsitesTable
          AWS_DYNAMODB_ENDPOINT: "http://127.0.0.1:8000"

  WebsitesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref WebsitesTable
      PrimaryKey:
        Name: pk
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebsitesAPI:
    Description: "API Gateway endpoint URL for Prod environment for Website Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/websites/"
  WebsitesFunction:
    Description: "Lambda Function ARN for Websites CRUD"
    Value: !GetAtt WebsitesFunction.Arn
  WebsitesFunctionIamRole:
    Description: "Implicit IAM Role created for Websites function"
    Value: !GetAtt WebsitesFunctionRole.Arn
